batch_size: 16384  # Use a reasonable batch size instead of 'all'
lr : 0.001
momentum: 0.5
epochs: 100000
val_split: 0.2
weight_decay: 0.0001
num_workers: 16  # Set to 0 for Windows to avoid multiprocessing issues
pin_memory: true  # Disable pin_memory for compatibility
prefetch_factor: 4  # Prefetch batches